-- MySQL Script generated by MySQL Workbench
-- Fri Jan  8 03:16:06 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Schema_Group07
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `Schema_Group07` ;

-- -----------------------------------------------------
-- Schema Schema_Group07
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Schema_Group07` DEFAULT CHARACTER SET utf8 ;
USE `Schema_Group07` ;

-- -----------------------------------------------------
-- Table `Schema_Group07`.`Student_Qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`Student_Qualification` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`Student_Qualification` (
  `student_id` INT(10) NOT NULL,
  `qualification_ID` INT(10) NOT NULL,
  PRIMARY KEY (`student_id`, `qualification_ID`),
  INDEX `fk_Student_Qualification_qualification1_idx` (`qualification_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Student_Qualification_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Schema_Group07`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_Qualification_qualification1`
    FOREIGN KEY (`qualification_ID`)
    REFERENCES `Schema_Group07`.`qualification` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`comments`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`comments` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`comments` (
  `CommentID` INT(10) NOT NULL,
  `Time` INT(10) NULL DEFAULT NULL,
  `Content` VARCHAR(255) NULL DEFAULT NULL,
  `student_id` INT(10) NOT NULL,
  PRIMARY KEY (`CommentID`),
  INDEX `fk_comments_student1_idx` (`student_id` ASC) VISIBLE,
  CONSTRAINT `fk_comments_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Schema_Group07`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`enquiresbystudent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`enquiresbystudent` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`enquiresbystudent` (
  `student_id` INT(10) NOT NULL,
  `enquiryinfo_EnquiryID` INT(10) NOT NULL,
  PRIMARY KEY (`student_id`, `enquiryinfo_EnquiryID`),
  INDEX `fk_enquiresbystudent_student1_idx` (`student_id` ASC) VISIBLE,
  INDEX `fk_enquiresbystudent_enquiryinfo1_idx` (`enquiryinfo_EnquiryID` ASC) VISIBLE,
  CONSTRAINT `fk_enquiresbystudent_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Schema_Group07`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_enquiresbystudent_enquiryinfo1`
    FOREIGN KEY (`enquiryinfo_EnquiryID`)
    REFERENCES `Schema_Group07`.`enquiryinfo` (`EnquiryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`enquiryinfo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`enquiryinfo` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`enquiryinfo` (
  `EnquiryID` INT(10) NOT NULL,
  `OccupationID` VARCHAR(255) NULL DEFAULT NULL,
  `IndustryID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`EnquiryID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`governmentdata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`governmentdata` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`governmentdata` (
  `Year` INT(10) NULL DEFAULT NULL,
  `IndustryID` VARCHAR(255) NULL DEFAULT NULL,
  `OccupationID` VARCHAR(255) NULL DEFAULT NULL,
  `Location` VARCHAR(255) NULL DEFAULT NULL,
  `NumOfJobs` INT(10) NULL DEFAULT NULL,
  `enquiryinfo_EnquiryID` INT(10) NOT NULL,
  CONSTRAINT `fk_governmentdata_enquiryinfo1`
    FOREIGN KEY (`enquiryinfo_EnquiryID`)
    REFERENCES `Schema_Group07`.`enquiryinfo` (`EnquiryID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`images` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`images` (
  `ImageID` INT(10) NOT NULL,
  `Content` INT(10) NULL DEFAULT NULL,
  PRIMARY KEY (`ImageID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`occupations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`occupations` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`occupations` (
  `OccupationID` INT(10) NOT NULL,
  `OccupationName` VARCHAR(225) NULL DEFAULT NULL,
  PRIMARY KEY (`OccupationID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`occupations_student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`occupations_student` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`occupations_student` (
  `student_id` INT(10) NOT NULL,
  `occupations_id` INT(10) NOT NULL,
  PRIMARY KEY (`student_id`, `occupations_id`),
  INDEX `fk_occupations_student_occupations1_idx` (`occupations_id` ASC) VISIBLE,
  CONSTRAINT `fk_occupations_student_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Schema_Group07`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_occupations_student_occupations1`
    FOREIGN KEY (`occupations_id`)
    REFERENCES `Schema_Group07`.`occupations` (`OccupationID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`qualification`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`qualification` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`qualification` (
  `ID` INT(10) NOT NULL,
  `QualificationName` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`savedimages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`savedimages` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`savedimages` (
  `student_id` INT(10) NOT NULL,
  `images_ImageID` INT(10) NOT NULL,
  PRIMARY KEY (`student_id`, `images_ImageID`),
  INDEX `fk_savedimages_images1_idx` (`images_ImageID` ASC) VISIBLE,
  CONSTRAINT `fk_savedimages_student1`
    FOREIGN KEY (`student_id`)
    REFERENCES `Schema_Group07`.`student` (`StudentID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_savedimages_images1`
    FOREIGN KEY (`images_ImageID`)
    REFERENCES `Schema_Group07`.`images` (`ImageID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `Schema_Group07`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `Schema_Group07`.`student` ;

CREATE TABLE IF NOT EXISTS `Schema_Group07`.`student` (
  `StudentID` INT(10) NOT NULL,
  `FirstName` VARCHAR(255) NULL DEFAULT NULL,
  `LastName` VARCHAR(255) NULL DEFAULT NULL,
  `Password` VARCHAR(255) NULL DEFAULT NULL,
  `Email` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`StudentID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
